/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Currency = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'rateToUSD' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'convert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'getCurrencies' : IDL.Func([], [IDL.Vec(Currency)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Currency = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'rateToUSD' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'convert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'getCurrencies' : IDL.Func([], [IDL.Vec(Currency)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };